# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20161107_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Photographer'),
            preserve_default=False,
        ),
    ]
