# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_category_photographer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='slug',
        ),
    ]
