# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20161107_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=32, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='photo',
            name='categories',
            field=models.ManyToManyField(to='gallery.Category'),
        ),
    ]
